import React, { useState, useRef, useEffect } from "react"
import { ToCData, Node } from "../types"
import { ShareIcon, AdjustmentsHorizontalIcon, EyeIcon, PencilIcon, ChevronDownIcon, TrashIcon, MinusIcon, PlusIcon, QuestionMarkCircleIcon, XMarkIcon, ClockIcon } from "@heroicons/react/24/outline"
import { ChartService, CreateChartResponse } from "../services/chartService"
import { shortcuts } from "../utils/keyboardShortcuts"
import { Tooltip } from 'react-tooltip'

interface EditToolbarProps {
  editMode: boolean
  setEditMode: React.Dispatch<React.SetStateAction<boolean>>
  showEditButton: boolean
  highlightedNodes: Set<string>
  setHighlightedNodes: React.Dispatch<React.SetStateAction<Set<string>>>
  layoutMode: boolean
  setLayoutMode: React.Dispatch<React.SetStateAction<boolean>>
  curvature: number
  setCurvature: React.Dispatch<React.SetStateAction<number>>
  textSize: number
  setTextSize: React.Dispatch<React.SetStateAction<number>>
  fontFamily: string
  setFontFamily: React.Dispatch<React.SetStateAction<string>>
  nodeWidth: number
  setNodeWidth: React.Dispatch<React.SetStateAction<number>>
  nodeColor: string
  setNodeColor: React.Dispatch<React.SetStateAction<string>>
  columnPadding: number
  setColumnPadding: React.Dispatch<React.SetStateAction<number>>
  sectionPadding: number
  setSectionPadding: React.Dispatch<React.SetStateAction<number>>
  straightenEdges: () => void
  setData: React.Dispatch<React.SetStateAction<ToCData>>
  // Header controls props
  undoHistory: ToCData[]
  redoHistory: ToCData[]
  handleUndo: () => void
  handleRedo: () => void
  isSaving: boolean
  currentEditToken: string | null
  lastSyncTime: Date | null
  isManualSyncing: boolean
  handleManualSync: () => void
  getTimeAgo: (date: Date) => string
  data: ToCData
  onDeleteNode?: (nodeId: string) => void
  nodePopup?: any
  edgePopup?: any
  // Camera props for toolbar positioning
  camera?: { x: number; y: number; z: number }
  // Callback to update the edit token when links are generated
  onEditTokenChange?: (token: string) => void
  // Container size for embed code generation
  containerSize?: { width: number; height: number }
}

export function EditToolbar({
  editMode,
  setEditMode,
  showEditButton,
  highlightedNodes,
  setHighlightedNodes,
  layoutMode,
  setLayoutMode,
  curvature,
  setCurvature,
  textSize,
  setTextSize,
  fontFamily,
  setFontFamily,
  nodeWidth,
  setNodeWidth,
  nodeColor,
  setNodeColor,
  columnPadding,
  setColumnPadding,
  sectionPadding,
  setSectionPadding,
  straightenEdges,
  setData,
  undoHistory,
  redoHistory,
  handleUndo,
  handleRedo,
  isSaving,
  currentEditToken,
  lastSyncTime,
  isManualSyncing,
  handleManualSync,
  getTimeAgo,
  data,
  onDeleteNode,
  nodePopup,
  edgePopup,
  camera,
  onEditTokenChange,
  containerSize,
}: EditToolbarProps) {
  const [showWidthDropdown, setShowWidthDropdown] = useState(false)
  const [showModeDropdown, setShowModeDropdown] = useState(false)
  const [showShareDropdown, setShowShareDropdown] = useState(false)
  const [showRecentDropdown, setShowRecentDropdown] = useState(false)
  const [showAlignmentSuggestion, setShowAlignmentSuggestion] = useState(false)
  const [showHelpModal, setShowHelpModal] = useState(false)
  const [toolbarPosition, setToolbarPosition] = useState({ x: 0, y: 0 })
  const [recentCharts, setRecentCharts] = useState<Array<{ title: string; editUrl: string; timestamp: number }>>([])


  // Tooltip state
  const [showLayoutTooltip, setShowLayoutTooltip] = useState(true)

  // Share functionality state
  const [shareData, setShareData] = useState<CreateChartResponse | null>(null)
  const [shareLoading, setShareLoading] = useState(false)
  const [shareError, setShareError] = useState<string | null>(null)
  const [copiedField, setCopiedField] = useState<string | null>(null)
  const [embedScale, setEmbedScale] = useState(1.0)

  const dropdownRef = useRef<HTMLDivElement>(null)
  const modeDropdownRef = useRef<HTMLDivElement>(null)
  const shareDropdownRef = useRef<HTMLDivElement>(null)
  const recentDropdownRef = useRef<HTMLDivElement>(null)
  const prevHighlightedNodesRef = useRef<Set<string>>(new Set())
  const hasAutoGeneratedRef = useRef(false)

  // Load recent charts from localStorage
  const loadRecentCharts = () => {
    try {
      const stored = localStorage.getItem('recentEditCharts')
      if (stored) {
        const charts = JSON.parse(stored)
        // Sort by timestamp, most recent first
        charts.sort((a: any, b: any) => b.timestamp - a.timestamp)
        // Keep only the 10 most recent
        setRecentCharts(charts.slice(0, 10))
      }
    } catch (error) {
      console.error('Failed to load recent charts:', error)
    }
  }

  // Save current chart to recent list
  const saveToRecent = (title: string, editUrl: string) => {
    try {
      const stored = localStorage.getItem('recentEditCharts')
      let charts = stored ? JSON.parse(stored) : []

      // Remove if already exists (to avoid duplicates)
      charts = charts.filter((c: any) => c.editUrl !== editUrl)

      // Add to beginning
      charts.unshift({
        title: title || 'Untitled Theory of Change',
        editUrl,
        timestamp: Date.now()
      })

      // Keep only 10 most recent
      charts = charts.slice(0, 10)

      localStorage.setItem('recentEditCharts', JSON.stringify(charts))
      setRecentCharts(charts)
    } catch (error) {
      console.error('Failed to save to recent charts:', error)
    }
  }

  // Remove a chart from recent list
  const removeFromRecent = (editUrl: string) => {
    try {
      const stored = localStorage.getItem('recentEditCharts')
      let charts = stored ? JSON.parse(stored) : []

      // Filter out the chart to remove
      charts = charts.filter((c: any) => c.editUrl !== editUrl)

      localStorage.setItem('recentEditCharts', JSON.stringify(charts))
      setRecentCharts(charts)
    } catch (error) {
      console.error('Failed to remove from recent charts:', error)
    }
  }

  // Load recent charts when component mounts or dropdown opens
  useEffect(() => {
    if (showRecentDropdown) {
      loadRecentCharts()
    }
  }, [showRecentDropdown])

  // Save current chart when we have an edit token
  useEffect(() => {
    if (currentEditToken && data) {
      const editUrl = `${window.location.origin}/edit/${currentEditToken}`
      const title = data.title || 'Theory of Change'
      saveToRecent(title, editUrl)
    }
  }, [currentEditToken, data?.title])

  // Smart detection for misaligned nodes
  const detectMisalignedNodes = (): boolean => {
    if (!editMode) return false

    const allNodes: { node: Node; centerY: number }[] = []

    // Collect all nodes with their Y positions
    data.sections.forEach((section) => {
      section.columns.forEach((column) => {
        column.nodes.forEach((node) => {
          const centerY = node.yPosition ?? 0
          allNodes.push({ node, centerY })
        })
      })
    })

    if (allNodes.length < 2) return false

    // Group nodes by similar Y positions (within tolerance)
    const tolerance = 40 // Same as straightenEdges function
    const groups: typeof allNodes[] = []

    allNodes.forEach((nodeData) => {
      let addedToGroup = false
      for (const group of groups) {
        const avgCenterY = group.reduce((sum, n) => sum + n.centerY, 0) / group.length
        if (Math.abs(nodeData.centerY - avgCenterY) <= tolerance) {
          group.push(nodeData)
          addedToGroup = true
          break
        }
      }
      if (!addedToGroup) {
        groups.push([nodeData])
      }
    })

    // Find misaligned groups
    const misalignedGroups = groups.filter(group => {
      if (group.length < 2) return false
      const positions = group.map(n => n.centerY)
      const min = Math.min(...positions)
      const max = Math.max(...positions)
      return (max - min) > 0 // Any difference = misaligned
    })

    return misalignedGroups.length > 0
  }

  // Share functionality functions
  const loadExistingShareData = async () => {
    if (!currentEditToken) return

    setShareLoading(true)
    setShareError(null)

    try {
      const chartId = await ChartService.getChartIdFromEditToken(currentEditToken)
      setShareData({
        chartId,
        editToken: currentEditToken,
        viewUrl: `${window.location.origin}/chart/${chartId}`,
        editUrl: `${window.location.origin}/edit/${currentEditToken}`
      })
    } catch (err) {
      setShareError(err instanceof Error ? err.message : 'Failed to load share data')
    } finally {
      setShareLoading(false)
    }
  }

  const handleShare = async () => {
    setShareLoading(true)
    setShareError(null)

    try {
      // If we already have an edit token, just update; otherwise create new
      if (currentEditToken) {
        await ChartService.updateChart(currentEditToken, data)
        // Get the correct chartId from the API
        const chartId = await ChartService.getChartIdFromEditToken(currentEditToken)
        setShareData({
          chartId,
          editToken: currentEditToken,
          viewUrl: `${window.location.origin}/chart/${chartId}`,
          editUrl: `${window.location.origin}/edit/${currentEditToken}`
        })
      } else {
        const response = await ChartService.createChart(data)
        setShareData(response)
        // Store the edit token locally
        ChartService.saveEditToken(response.chartId, response.editToken)
        // Update the URL to the edit URL
        window.history.replaceState(null, '', `/edit/${response.editToken}`)
        // Notify parent component about the new edit token
        if (onEditTokenChange) {
          onEditTokenChange(response.editToken)
        }
      }
    } catch (err) {
      setShareError(err instanceof Error ? err.message : 'Failed to share chart')
    } finally {
      setShareLoading(false)
    }
  }

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopiedField(field)
      setTimeout(() => setCopiedField(null), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  // Check for misalignment when data changes
  useEffect(() => {
    const hasMisaligned = detectMisalignedNodes()
    if (editMode && hasMisaligned) {
      setShowAlignmentSuggestion(true)
    } else {
      setShowAlignmentSuggestion(false)
    }
  }, [data, editMode])

  // Auto-generate share links on first edit (without opening dropdown)
  useEffect(() => {
    if (!currentEditToken && !hasAutoGeneratedRef.current && undoHistory.length > 0) {
      // First edit detected (undo history has entries) - auto-generate share links
      hasAutoGeneratedRef.current = true
      handleShare()
    }
  }, [currentEditToken, undoHistory.length])

  // Auto-generate or load share data when dropdown opens
  useEffect(() => {
    if (showShareDropdown && !shareData && !shareLoading) {
      if (currentEditToken) {
        // If we have an edit token, load existing share data
        loadExistingShareData()
      } else {
        // Otherwise, create new share links
        handleShare()
      }
    } else if (!showShareDropdown) {
      // Reset state when dropdown closes
      setShareData(null)
      setShareError(null)
      setCopiedField(null)
      setEmbedScale(1.0) // Reset scale to 100%
    }
  }, [showShareDropdown])

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowWidthDropdown(false)
      }
      if (modeDropdownRef.current && !modeDropdownRef.current.contains(event.target as Node)) {
        setShowModeDropdown(false)
      }
      if (shareDropdownRef.current && !shareDropdownRef.current.contains(event.target as Node)) {
        setShowShareDropdown(false)
      }
      if (recentDropdownRef.current && !recentDropdownRef.current.contains(event.target as Node)) {
        setShowRecentDropdown(false)
      }
    }

    if (showWidthDropdown || showModeDropdown || showShareDropdown || showRecentDropdown) {
      document.addEventListener('mousedown', handleClickOutside)
      return () => document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [showWidthDropdown, showModeDropdown, showShareDropdown, showRecentDropdown])

  // Update toolbar position when selection changes or camera changes
  useEffect(() => {
    if (highlightedNodes.size === 0) return;

    // Calculate new position
    const nodeElements = Array.from(highlightedNodes).map(nodeId =>
      document.getElementById(`node-${nodeId}`)
    ).filter(Boolean);

    if (nodeElements.length > 0) {
      const rects = nodeElements.map(el => el.getBoundingClientRect());
      const avgX = rects.reduce((sum, rect) => sum + rect.left + rect.width / 2, 0) / rects.length;
      const topY = Math.min(...rects.map(rect => rect.top));

      setToolbarPosition({ x: avgX, y: topY - 80 });
    }

    prevHighlightedNodesRef.current = new Set(highlightedNodes);
  }, [highlightedNodes, camera?.x, camera?.y, camera?.z])

  if (!showEditButton) return null

  return (
    <>
      <div className="fixed top-0 left-0 right-0 z-50 bg-white border-b border-gray-300 shadow-sm">
        <div className="max-w-none mx-auto py-2" style={{ maxWidth: '100%' }}>
        <div className="flex items-center justify-between relative">
          {/* Left side - Header controls and main tools */}
          <div className="flex items-center gap-4 flex-1 pl-2">
            {/* Open Recent Dropdown - Far Left */}
            <div className="relative" ref={recentDropdownRef}>
              <button
                onClick={() => setShowRecentDropdown(!showRecentDropdown)}
                className="px-3 py-2 text-gray-600 hover:bg-gray-100 text-sm font-medium rounded transition-all duration-200 flex items-center gap-2"
                title="Open recent charts"
              >
                <ClockIcon className="w-4 h-4" />
                Open Recent
                <ChevronDownIcon className="w-3 h-3" />
              </button>

              {/* Recent Charts Dropdown */}
              {showRecentDropdown && (
                <div className="absolute top-full mt-2 left-0 w-80 bg-white rounded-lg shadow-lg border border-gray-200 z-50 max-h-96 overflow-y-auto">
                  <div className="p-2">
                    {recentCharts.length === 0 ? (
                      <div className="px-3 py-4 text-sm text-gray-500 text-center">
                        No recent charts yet
                      </div>
                    ) : (
                      <div className="space-y-1">
                        {recentCharts.map((chart, index) => {
                          const isCurrentChart = chart.editUrl === `${window.location.origin}/edit/${currentEditToken}`
                          return (
                            <div
                              key={index}
                              className={`group flex items-start gap-2 px-3 py-2 rounded text-sm transition-colors ${
                                isCurrentChart
                                  ? 'bg-blue-50'
                                  : 'hover:bg-gray-100'
                              }`}
                            >
                              <a
                                href={chart.editUrl}
                                onClick={(e) => {
                                  if (isCurrentChart) {
                                    e.preventDefault()
                                    setShowRecentDropdown(false)
                                  }
                                }}
                                className={`flex-1 min-w-0 ${
                                  isCurrentChart
                                    ? 'text-blue-700 cursor-default'
                                    : 'text-gray-700'
                                }`}
                              >
                                <div className="font-medium truncate">
                                  {chart.title}
                                </div>
                                <div className="text-xs text-gray-500 mt-0.5">
                                  {new Date(chart.timestamp).toLocaleDateString()} at {new Date(chart.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                  {isCurrentChart && <span className="ml-2 text-blue-600">(Current)</span>}
                                </div>
                              </a>
                              <button
                                onClick={(e) => {
                                  e.preventDefault()
                                  e.stopPropagation()
                                  removeFromRecent(chart.editUrl)
                                }}
                                className="opacity-0 group-hover:opacity-100 p-1 text-gray-400 hover:text-gray-600 hover:bg-gray-200 rounded transition-all duration-200"
                                title="Remove from recent"
                              >
                                <XMarkIcon className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          )
                        })}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>

            {/* Separator */}
            <div className="h-6 w-px bg-gray-300"></div>

            {/* Undo/Redo Group */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">({undoHistory.length})</span>
              <button
                onClick={handleUndo}
                disabled={undoHistory.length === 0}
                className="p-2 text-gray-600 hover:bg-gray-100 hover:text-gray-800 rounded disabled:opacity-40 disabled:cursor-not-allowed transition-all duration-200"
                title={`Undo (${shortcuts.undoDisplay()})`}
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
                </svg>
              </button>
              <button
                onClick={handleRedo}
                disabled={redoHistory.length === 0}
                className="p-2 text-gray-600 hover:bg-gray-100 hover:text-gray-800 rounded disabled:opacity-40 disabled:cursor-not-allowed transition-all duration-200"
                title={`Redo (${shortcuts.redoDisplay()})`}
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 10H11a8 8 0 00-8 8v2m18-10l-6 6m6-6l-6-6" />
                </svg>
              </button>
              <span className="text-xs text-gray-500">({redoHistory.length})</span>
            </div>

            {/* Separator */}
            <div className="h-6 w-px bg-gray-300 mx-1"></div>

            {/* Edit Tools */}
            <div className="flex items-center gap-1">
              <button
                onClick={() => editMode && setLayoutMode(!layoutMode)}
                disabled={!editMode}
                data-tooltip-id="layout-mode-tooltip"
                className={`p-2 rounded transition-all duration-200 ${
                  !editMode
                    ? 'text-gray-400 cursor-not-allowed'
                    : layoutMode
                    ? 'bg-blue-100 text-blue-700 hover:bg-blue-200'
                    : 'text-gray-600 hover:bg-gray-100 hover:text-gray-800'
                }`}
                title={`Layout Mode: ${layoutMode ? 'On' : 'Off'}`}
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 5a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM14 5a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1V5zM4 15a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1H5a1 1 0 01-1-1v-4zM14 15a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z" />
                </svg>
              </button>

              {/* Text Size Control - Google Drive Style */}
              <div className={`flex items-center gap-1 px-1 py-1 rounded transition-colors ${
                editMode ? 'hover:bg-gray-100' : 'opacity-50 cursor-not-allowed'
              }`}>
                <button
                  onClick={() => {
                    if (!editMode) return;
                    const currentPx = Math.round(textSize * 18);
                    const newPx = Math.max(9, currentPx - 1);
                    setTextSize(newPx / 18);
                  }}
                  disabled={!editMode}
                  className={`p-1 rounded transition-colors ${
                    editMode ? 'hover:bg-gray-200' : 'cursor-not-allowed'
                  }`}
                  title="Decrease text size"
                >
                  <MinusIcon className="w-4 h-4 text-gray-600" />
                </button>
                <input
                  type="number"
                  value={Math.round(textSize * 18)}
                  onChange={(e) => {
                    if (!editMode) return;
                    const px = parseInt(e.target.value) || 18;
                    const clampedPx = Math.max(9, Math.min(36, px));
                    setTextSize(clampedPx / 18);
                  }}
                  disabled={!editMode}
                  className="w-10 text-sm text-gray-700 font-medium text-center border-0 focus:outline-none focus:ring-1 focus:ring-blue-500 rounded [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none disabled:cursor-not-allowed"
                  min="9"
                  max="36"
                />
                <button
                  onClick={() => {
                    if (!editMode) return;
                    const currentPx = Math.round(textSize * 18);
                    const newPx = Math.min(36, currentPx + 1);
                    setTextSize(newPx / 18);
                  }}
                  disabled={!editMode}
                  className={`p-1 rounded transition-colors ${
                    editMode ? 'hover:bg-gray-200' : 'cursor-not-allowed'
                  }`}
                  title="Increase text size"
                >
                  <PlusIcon className="w-4 h-4 text-gray-600" />
                </button>
              </div>

              {/* Font Family Dropdown */}
              <div className={`flex items-center gap-1 px-2 rounded transition-colors ${
                editMode ? 'hover:bg-gray-100' : 'opacity-50 cursor-not-allowed'
              }`}>
                <select
                  value={fontFamily}
                  onChange={(e) => {
                    if (!editMode) return;
                    setFontFamily(e.target.value);
                  }}
                  disabled={!editMode}
                  className="text-sm text-gray-700 border-0 focus:outline-none focus:ring-1 focus:ring-blue-500 rounded px-1 disabled:cursor-not-allowed bg-transparent max-w-[110px]"
                  style={{ fontFamily: fontFamily }}
                  title="Font family"
                >
                  <option value="'Roboto', sans-serif" style={{ fontFamily: "'Roboto', sans-serif" }}>Roboto</option>
                  <option value="'Open Sans', sans-serif" style={{ fontFamily: "'Open Sans', sans-serif" }}>Open Sans</option>
                  <option value="'Lato', sans-serif" style={{ fontFamily: "'Lato', sans-serif" }}>Lato</option>
                  <option value="'Montserrat', sans-serif" style={{ fontFamily: "'Montserrat', sans-serif" }}>Montserrat</option>
                  <option value="'Oswald', sans-serif" style={{ fontFamily: "'Oswald', sans-serif" }}>Oswald</option>
                  <option value="'Source Sans Pro', sans-serif" style={{ fontFamily: "'Source Sans Pro', sans-serif" }}>Source Sans Pro</option>
                  <option value="'Raleway', sans-serif" style={{ fontFamily: "'Raleway', sans-serif" }}>Raleway</option>
                  <option value="'Poppins', sans-serif" style={{ fontFamily: "'Poppins', sans-serif" }}>Poppins</option>
                  <option value="'Merriweather', serif" style={{ fontFamily: "'Merriweather', serif" }}>Merriweather</option>
                  <option value="'PT Sans', sans-serif" style={{ fontFamily: "'PT Sans', sans-serif" }}>PT Sans</option>
                  <option value="'Ubuntu', sans-serif" style={{ fontFamily: "'Ubuntu', sans-serif" }}>Ubuntu</option>
                  <option value="'Playfair Display', serif" style={{ fontFamily: "'Playfair Display', serif" }}>Playfair Display</option>
                  <option value="'Noto Sans', sans-serif" style={{ fontFamily: "'Noto Sans', sans-serif" }}>Noto Sans</option>
                  <option value="'Nunito', sans-serif" style={{ fontFamily: "'Nunito', sans-serif" }}>Nunito</option>
                  <option value="'Mukta', sans-serif" style={{ fontFamily: "'Mukta', sans-serif" }}>Mukta</option>
                  <option value="'Rubik', sans-serif" style={{ fontFamily: "'Rubik', sans-serif" }}>Rubik</option>
                  <option value="'Work Sans', sans-serif" style={{ fontFamily: "'Work Sans', sans-serif" }}>Work Sans</option>
                  <option value="'Lora', serif" style={{ fontFamily: "'Lora', serif" }}>Lora</option>
                  <option value="'Noto Serif', serif" style={{ fontFamily: "'Noto Serif', serif" }}>Noto Serif</option>
                  <option value="'Roboto Condensed', sans-serif" style={{ fontFamily: "'Roboto Condensed', sans-serif" }}>Roboto Condensed</option>
                  <option value="'PT Serif', serif" style={{ fontFamily: "'PT Serif', serif" }}>PT Serif</option>
                  <option value="'Quicksand', sans-serif" style={{ fontFamily: "'Quicksand', sans-serif" }}>Quicksand</option>
                  <option value="'Roboto Slab', serif" style={{ fontFamily: "'Roboto Slab', serif" }}>Roboto Slab</option>
                  <option value="'Oxygen', sans-serif" style={{ fontFamily: "'Oxygen', sans-serif" }}>Oxygen</option>
                  <option value="'Slabo 27px', serif" style={{ fontFamily: "'Slabo 27px', serif" }}>Slabo 27px</option>
                  <option value="'Fira Sans', sans-serif" style={{ fontFamily: "'Fira Sans', sans-serif" }}>Fira Sans</option>
                  <option value="'Karla', sans-serif" style={{ fontFamily: "'Karla', sans-serif" }}>Karla</option>
                  <option value="'Titillium Web', sans-serif" style={{ fontFamily: "'Titillium Web', sans-serif" }}>Titillium Web</option>
                  <option value="'Arimo', sans-serif" style={{ fontFamily: "'Arimo', sans-serif" }}>Arimo</option>
                  <option value="'Cabin', sans-serif" style={{ fontFamily: "'Cabin', sans-serif" }}>Cabin</option>
                </select>
              </div>

              {/* More Tools Dropdown */}
              <div className="relative" ref={dropdownRef}>
                <button
                  onClick={() => editMode && setShowWidthDropdown(!showWidthDropdown)}
                  disabled={!editMode}
                  className={`p-2 rounded transition-all duration-200 ${
                    editMode
                      ? 'text-gray-600 hover:bg-gray-100 hover:text-gray-800'
                      : 'text-gray-400 cursor-not-allowed'
                  }`}
                  title="More formatting options"
                >
                  <AdjustmentsHorizontalIcon className="w-5 h-5" />
                </button>

                {/* Dropdown Menu */}
                {showWidthDropdown && (
                  <div className="absolute top-full mt-2 left-0 w-64 bg-white rounded-lg shadow-lg border border-gray-200 py-2 z-50">
                    <div className="px-4 py-3 border-b border-gray-100">
                      <h4 className="text-sm font-medium text-gray-700">Formatting Options</h4>
                    </div>

                    <div className="p-4 space-y-4">
                      {/* Curve Control */}
                      <div>
                        <label className="text-sm text-gray-600">Connection Curve</label>
                        <div className="flex items-center gap-2 mt-2">
                          <input
                            type="range"
                            min="0"
                            max="1"
                            step="0.1"
                            value={curvature}
                            onChange={(e) => setCurvature(parseFloat(e.target.value))}
                            className="flex-1 h-1 rounded-lg appearance-none cursor-pointer bg-gray-200"
                          />
                          <span className="text-xs text-gray-500 w-12">{Math.round(curvature * 100)}%</span>
                        </div>
                      </div>

                      {/* Spacing Controls */}
                      <div>
                        <label className="text-sm text-gray-600">Column Spacing</label>
                        <div className="flex items-center gap-2 mt-2">
                          <input
                            type="range"
                            min="0"
                            max="100"
                            step="4"
                            value={columnPadding}
                            onChange={(e) => setColumnPadding(parseInt(e.target.value))}
                            className="flex-1 h-1 rounded-lg appearance-none cursor-pointer bg-gray-200"
                          />
                          <span className="text-xs text-gray-500 w-12">{columnPadding}px</span>
                        </div>
                      </div>

                      <div>
                        <label className="text-sm text-gray-600">Section Spacing</label>
                        <div className="flex items-center gap-2 mt-2">
                          <input
                            type="range"
                            min="0"
                            max="100"
                            step="4"
                            value={sectionPadding}
                            onChange={(e) => setSectionPadding(parseInt(e.target.value))}
                            className="flex-1 h-1 rounded-lg appearance-none cursor-pointer bg-gray-200"
                          />
                          <span className="text-xs text-gray-500 w-12">{sectionPadding}px</span>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Center - Share Dropdown */}
          <div className="absolute left-1/2 transform -translate-x-1/2 z-10" ref={shareDropdownRef}>
            <button
              onClick={() => setShowShareDropdown(!showShareDropdown)}
              className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded hover:bg-blue-700 transition-all duration-200 flex items-center gap-2"
              title="Share"
            >
              <ShareIcon className="w-4 h-4" />
              Share
            </button>

            {/* Share Dropdown */}
            {showShareDropdown && (
              <div className="absolute top-full mt-2 left-1/2 transform -translate-x-1/2 w-96 bg-white rounded-lg shadow-lg border border-gray-200 p-4 z-50 max-h-96 overflow-y-auto">
                <div>
                  {shareLoading && (
                    <div className="text-center py-4">
                      <div className="inline-block animate-spin rounded-full h-6 w-6 border-b-2 border-indigo-600"></div>
                      <p className="mt-2 text-gray-600 text-sm">
                        {currentEditToken ? 'Loading share links...' : 'Creating shareable links...'}
                      </p>
                    </div>
                  )}

                  {shareError && (
                    <div className="bg-red-50 border border-red-200 rounded-lg p-3 mb-4">
                      <p className="text-red-600 text-sm">{shareError}</p>
                      <button
                        onClick={() => {
                          setShareError(null)
                          if (currentEditToken) {
                            loadExistingShareData()
                          } else {
                            handleShare()
                          }
                        }}
                        className="mt-2 text-sm text-red-700 underline hover:no-underline"
                      >
                        Try again
                      </button>
                    </div>
                  )}

                  {shareData && !shareLoading && (
                    <div className="space-y-4">
                      

                      <div>
                        <label className="block text-xs font-medium text-gray-700 mb-1">
                          Edit Link
                        </label>
                        <div className="flex items-center gap-2">
                          <input
                            type="text"
                            readOnly
                            value={shareData.editUrl}
                            className="flex-1 px-2 py-1 border border-gray-300 rounded text-xs bg-yellow-50"
                          />
                          <button
                            onClick={() => copyToClipboard(shareData.editUrl, 'edit')}
                            className="px-2 py-1 text-xs bg-yellow-100 text-yellow-800 rounded hover:bg-yellow-200 transition-colors"
                          >
                            {copiedField === 'edit' ? 'Copied!' : 'Copy'}
                          </button>
                        </div>
                        <p className="text-xs text-yellow-700 mt-2">
                          Keep this link private - anyone with it can edit your chart
                        </p>
                      </div>

                      <div>
                        <label className="block text-xs font-medium text-gray-700 mb-1">
                          View Link
                        </label>
                        <div className="flex items-center gap-2">
                          <input
                            type="text"
                            readOnly
                            value={shareData.viewUrl}
                            className="flex-1 px-2 py-1 border border-gray-300 rounded text-xs bg-gray-50"
                          />
                          <button
                            onClick={() => copyToClipboard(shareData.viewUrl, 'view')}
                            className="px-2 py-1 text-xs bg-gray-100 text-gray-700 rounded hover:bg-gray-200 transition-colors"
                          >
                            {copiedField === 'view' ? 'Copied!' : 'Copy'}
                          </button>
                        </div>
                        <p className="text-xs text-gray-500 mt-2">
                          Share this link with anyone to view your chart
                        </p>
                      </div>

                      <div>
                        <label className="block text-xs font-medium text-gray-700 mb-1">
                          Embed Code
                        </label>

                        <div className="flex items-start gap-2">
                          <textarea
                            readOnly
                            value={`<iframe src="${shareData.viewUrl}" width="100%" height="unset" frameborder="0" style="border: none; aspect-ratio: ${containerSize?.width || 16} / ${containerSize?.height || 9};" allowfullscreen></iframe>`}
                            className="flex-1 px-2 py-1 border border-gray-300 rounded text-xs bg-blue-50 font-mono resize-none overflow-hidden"
                            rows={6}
                            style={{ lineHeight: '1.5' }}
                          />
                          <button
                            onClick={() => {
                              copyToClipboard(
                                `<iframe src="${shareData.viewUrl}" width="100%" height="unset" frameborder="0" style="border: none; aspect-ratio: ${containerSize?.width || 16} / ${containerSize?.height || 9};" allowfullscreen></iframe>`,
                                'embed'
                              );
                            }}
                            className="px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded hover:bg-blue-200 transition-colors whitespace-nowrap"
                          >
                            {copiedField === 'embed' ? 'Copied!' : 'Copy'}
                          </button>
                        </div>
                        <p className="text-xs text-gray-600 mt-2">
                          Embed instructions: <a href="https://wordpress.org/documentation/article/wordpress-block-editor/#custom-html" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-700">WordPress</a>, <a href="https://support.wix.com/en/article/studio-editor-adding-an-html-iframe-element" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-700">Wix</a>, <a href="https://support.squarespace.com/hc/en-us/articles/206543617-Code-Blocks" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-700">Squarespace</a>, <a href="https://university.webflow.com/lesson/custom-code-embed" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-700">Webflow</a>
                        </p>
                      </div>

                      <div className="pt-3 border-t border-gray-200">
                        <p className="text-xs text-gray-600">
                          Chart ID: <code className="bg-gray-100 px-1 rounded text-xs">{shareData.chartId}</code>
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Right side - Visual Controls and Actions */}
          <div className="flex items-center gap-1 flex-1 justify-end pr-2">

            {/* Save Status */}
            <div className="flex items-center gap-2">
              {isSaving && (
                <div className="flex items-center gap-1 px-2 py-1 text-gray-600 text-sm">
                  <svg className="animate-spin w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <span>Saving...</span>
                </div>
              )}
              {!isSaving && currentEditToken && (
                <div className="flex items-center gap-1 px-2 py-1 text-gray-600 text-sm">
                  <svg className="w-4 h-4 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                  </svg>
                  <span>Saved</span>
                </div>
              )}
              {currentEditToken && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleManualSync}
                    disabled={isManualSyncing}
                    className="p-2 text-gray-600 hover:bg-gray-100 hover:text-gray-800 rounded disabled:opacity-40 disabled:cursor-not-allowed transition-all duration-200"
                    title="Sync with server"
                  >
                    <svg className={`w-5 h-5 ${isManualSyncing ? 'animate-spin' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                  </button>
                  {lastSyncTime && (
                    <span className="text-gray-600 text-sm">Last synced: {getTimeAgo(lastSyncTime)}</span>
                  )}
                </div>
              )}
            </div>

            {/* Separator */}
            <div className="h-6 w-px bg-gray-300 mx-2"></div>

            {/* Help Button */}
            <button
              onClick={() => setShowHelpModal(true)}
              className="p-2 text-gray-600 hover:bg-gray-100 hover:text-gray-800 rounded transition-all duration-200"
              title="Help & Keyboard Shortcuts"
            >
              <QuestionMarkCircleIcon className="w-5 h-5" />
            </button>

            {/* Separator */}
            <div className="h-6 w-px bg-gray-300 mx-2"></div>

            {/* Mode Switcher Dropdown (Google Docs style) */}
            <div className="relative" ref={modeDropdownRef}>
              <button
                onClick={() => setShowModeDropdown(!showModeDropdown)}
                className="flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-100 rounded transition-all duration-200"
              >
                {editMode ? (
                  <>
                    <PencilIcon className="w-4 h-4" />
                    <span>Editing</span>
                  </>
                ) : (
                  <>
                    <EyeIcon className="w-4 h-4" />
                    <span>Viewing</span>
                  </>
                )}
                <ChevronDownIcon className="w-4 h-4 text-gray-500" />
              </button>

              {showModeDropdown && (
                <div className="absolute top-full right-0 mt-2 w-48 bg-white rounded-md shadow-lg border border-gray-200 py-1 z-50">
                  <button
                    onClick={() => {
                      setEditMode(true)
                      setShowModeDropdown(false)
                    }}
                    className={`w-full flex items-center gap-3 px-4 py-2 text-sm transition-colors ${
                      editMode
                        ? 'bg-blue-50 text-blue-700'
                        : 'text-gray-700 hover:bg-gray-100'
                    }`}
                  >
                    <PencilIcon className="w-4 h-4" />
                    <span>Editing</span>
                    {editMode && (
                      <svg className="w-4 h-4 ml-auto text-blue-700" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                    )}
                  </button>
                  <button
                    onClick={() => {
                      setEditMode(false)
                      setHighlightedNodes(new Set())
                      setLayoutMode(false)
                      setShowModeDropdown(false)
                    }}
                    className={`w-full flex items-center gap-3 px-4 py-2 text-sm transition-colors ${
                      !editMode
                        ? 'bg-blue-50 text-blue-700'
                        : 'text-gray-700 hover:bg-gray-100'
                    }`}
                  >
                    <EyeIcon className="w-4 h-4" />
                    <span>Viewing</span>
                    {!editMode && (
                      <svg className="w-4 h-4 ml-auto text-blue-700" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                    )}
                  </button>
                </div>
              )}
            </div>

          </div>
        </div>
      </div>
      </div>

      {/* Help Modal */}
      {showHelpModal && (
        <div
          className="fixed inset-0 z-[70] flex items-center justify-center bg-black bg-opacity-50"
          onClick={() => setShowHelpModal(false)}
        >
          <div
            className="bg-white rounded-lg shadow-xl max-w-2xl max-h-[80vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
              <h2 className="text-xl font-semibold text-gray-800">Help & Keyboard Shortcuts</h2>
              <button
                onClick={() => setShowHelpModal(false)}
                className="p-1 text-gray-400 hover:text-gray-600 rounded transition-colors"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <div className="px-6 py-4">
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">Basic Navigation</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>Click nodes</strong> to select</li>
                    <li>• <strong>Hover</strong> to highlight connections</li>
                    <li>• <strong>Tab</strong> to navigate nodes</li>
                    <li>• <strong>Escape</strong> to clear selections</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">Node Selection</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>Click:</strong> Select single node</li>
                    <li>• <strong>{shortcuts.multiSelect()}:</strong> Multi-select</li>
                    <li>• <strong>Shift+Click:</strong> Select column</li>
                    <li>• <strong>{shortcuts.selectAllDisplay()}:</strong> Select all (edit mode)</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">Edit Mode</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>Double-click:</strong> Create node</li>
                    <li>• <strong>Drag nodes</strong> to reposition</li>
                    <li>• <strong>Select 2 nodes:</strong> Connect/disconnect</li>
                    <li>• <strong>Delete:</strong> Remove selected</li>
                    <li>• <strong>Arrow keys:</strong> Fine-tune position</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">Keyboard Shortcuts</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>{shortcuts.undoDisplay()}:</strong> Undo</li>
                    <li>• <strong>{shortcuts.redoDisplay()}:</strong> Redo</li>
                    <li>• <strong>↑↓:</strong> Move vertically</li>
                    <li>• <strong>←→:</strong> Move between columns</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">Connections</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>Solid:</strong> High confidence (75-100%)</li>
                    <li>• <strong>Dashed:</strong> Medium (25-75%)</li>
                    <li>• <strong>Dotted:</strong> Low (0-25%)</li>
                    <li>• <strong>Click line:</strong> Edit confidence</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-3">AI Assistant</h3>
                  <ul className="space-y-2 text-sm text-gray-700">
                    <li>• <strong>Chat panel</strong> on the left</li>
                    <li>• <strong>Ask questions</strong> about ToC</li>
                    <li>• <strong>Request edits</strong> to nodes</li>
                    <li>• <strong>Generate content</strong> for sections</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="sticky bottom-0 bg-gray-50 border-t border-gray-200 px-6 py-3">
              <button
                onClick={() => setShowHelpModal(false)}
                className="w-full px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
              >
                Got it
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Smart Alignment Suggestion Popup */}
      {showAlignmentSuggestion && (
        <div
          className="absolute z-50 bg-white rounded-lg shadow-lg border border-gray-200 px-2 py-2 max-w-xs transition-all duration-300 ease-out"
          style={{
            right: '20px',
            bottom: '20px'
          }}
        >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="flex items-center justify-center gap-3 w-full">
                {/* Misaligned nodes */}
                <svg className="w-12 h-12 text-blue-600" fill="currentColor" stroke="currentColor" viewBox="0 0 24 24">
                  <rect x="2" y="8" width="3" height="8" rx="1.5" opacity="0.7" />
                  <rect x="8" y="10" width="3" height="8" rx="1.5" opacity="0.7" />
                  <rect x="14" y="7" width="3" height="8" rx="1.5" opacity="0.7" />
                </svg>

                {/* Arrow */}
                <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h8m0 0l-3-3m3 3l-3 3" />
                </svg>

                {/* Aligned nodes */}
                <svg className="w-12 h-12 text-blue-600" fill="currentColor" stroke="currentColor" viewBox="0 0 24 24">
                  <rect x="2" y="8" width="3" height="8" rx="1.5" opacity="0.7" />
                  <rect x="8" y="8" width="3" height="8" rx="1.5" opacity="0.7" />
                  <rect x="14" y="8" width="3" height="8" rx="1.5" opacity="0.7" />
                </svg>
              </div>
              <div>
                <div className="text-sm font-medium text-gray-900 mb-1">
                  Clean up alignment?
                </div>
                <div className="text-xs text-gray-600 mb-3">
                  Some nodes are close but not perfectly aligned
                </div>
                <div className="flex gap-2 justify-center">
                  <button
                    onClick={() => {
                      straightenEdges()
                      setShowAlignmentSuggestion(false)
                    }}
                    className="px-3 py-1.5 bg-blue-600 text-white text-xs font-medium rounded hover:bg-blue-700 transition-colors"
                  >
                    Align nodes
                  </button>
                  <button
                    onClick={() => setShowAlignmentSuggestion(false)}
                    className="px-3 py-1.5 text-gray-600 text-xs rounded hover:bg-gray-100 transition-colors"
                  >
                    Dismiss
                  </button>
                </div>
              </div>
            </div>
        </div>
      )}

      {/* Node Selection Popup - Miro Style Horizontal Bar */}
      {editMode && highlightedNodes.size > 0 && !showHelpModal && !nodePopup && !edgePopup && (
        <div
          className="fixed z-[60] bg-white rounded-lg shadow-lg border border-gray-200 px-4 py-3"
          style={{
            left: toolbarPosition.x,
            top: toolbarPosition.y,
            transform: 'translateX(-50%)',
            minWidth: '400px'
          }}
          >
            <div className="flex items-center gap-6">
              {/* Node Count */}
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-gray-700">
                  {highlightedNodes.size === 1 ? '' : `${highlightedNodes.size} nodes selected`}
                </span>
              </div>

              {/* Separator if more than 1 node */}
              {highlightedNodes.size > 1 && (
                <div className="h-4 w-px bg-gray-300"></div>
              )}

              {/* Width Control */}
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-600">Width</span>
                <input
                  type="range"
                  min="128"
                  max="320"
                  step="16"
                  value={nodeWidth}
                  onChange={(e) => {
                    const newWidth = parseInt(e.target.value)
                    setNodeWidth(newWidth)
                    if (highlightedNodes.size > 0) {
                      setData((prevData) => ({
                        ...prevData,
                        sections: prevData.sections.map((section) => ({
                          ...section,
                          columns: section.columns.map((column) => ({
                            ...column,
                            nodes: column.nodes.map((node) => {
                              if (highlightedNodes.has(node.id)) {
                                return { ...node, width: newWidth }
                              }
                              return node
                            })
                          }))
                        }))
                      }))
                    }
                  }}
                  className="w-20 h-1 rounded-lg appearance-none cursor-pointer bg-gray-200"
                />
                <span className="text-xs text-gray-500 w-10 text-right">{nodeWidth}px</span>
              </div>

              {/* Separator */}
              <div className="h-4 w-px bg-gray-300"></div>

              {/* Color Control */}
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-600">Color</span>
                <input
                  type="color"
                  value={nodeColor}
                  onChange={(e) => {
                    const newColor = e.target.value
                    setNodeColor(newColor)
                    if (highlightedNodes.size > 0) {
                      setData((prevData) => ({
                        ...prevData,
                        sections: prevData.sections.map((section) => ({
                          ...section,
                          columns: section.columns.map((column) => ({
                            ...column,
                            nodes: column.nodes.map((node) => {
                              if (highlightedNodes.has(node.id)) {
                                return { ...node, color: newColor }
                              }
                              return node
                            })
                          }))
                        }))
                      }))
                    }
                  }}
                  className="w-8 h-8 rounded border border-gray-300 cursor-pointer"
                />
              </div>

              {/* Delete Button - only in edit mode */}
              {editMode && onDeleteNode && (
                <>
                  {/* Separator */}
                  <div className="h-4 w-px bg-gray-300"></div>

                  <button
                    onClick={() => {
                      // Delete all selected nodes
                      highlightedNodes.forEach(nodeId => {
                        onDeleteNode(nodeId)
                      })
                      // Clear selection after deleting
                      setHighlightedNodes(new Set())
                    }}
                    className="p-2 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded transition-all duration-200"
                    title={`Delete ${highlightedNodes.size === 1 ? 'node' : 'nodes'}`}
                  >
                    <TrashIcon className="w-5 h-5" />
                  </button>
                </>
              )}
            </div>
          </div>
      )}

      {/* Layout Mode Tooltip */}
      {editMode && (
        <Tooltip
          id="layout-mode-tooltip"
          place="bottom"
          isOpen={showLayoutTooltip}
          clickable
          style={{ zIndex: 9999 }}
        >
          <div>
            <div>Add/remove columns & sections</div>
            <button
              onClick={() => setShowLayoutTooltip(false)}
              className="text-xs underline hover:no-underline mt-2"
            >
              Got it
            </button>
          </div>
        </Tooltip>
      )}
    </>
  )
}